spring.application.name=25AD052-PROJECT
spring.datasource.url=jdbc:mysql://localhost:3306/SOLARSHARE
spring.datasource.username=root
spring.datasource.password=Giri2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
